### ISSUE TITLE
already defined error

### ISSUE THREAD

**Issue by xxroot** [OrangeFoxRecovery/device_xiaomi_garden#1]
sapphire@admin:/media/sapphire/D/Fox/Fox_11.0$ export ALLOW_MISSING_DEPENDENCIES=true
sapphire@admin:/media/sapphire/D/Fox/Fox_11.0$ make recoveryimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=twrp_garden
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.8.0-61-generic-x86_64-Deepin-15
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ1A.210205.004
OUT_DIR=out
============================================
[100% 1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
FAILED: out/soong/.bootstrap/build.ninja
out/soong/.minibootstrap/minibp -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/.bootstrap/build.ninja.d
 -globFile out/soong/.minibootstrap/build-globs.ninja -o out/soong/.bootstrap/build.ninja Android.bp
error: Fox_11.0/bootable/recovery/Android.bp:20:1: module "soong-libaosprecovery_defaults" already defined
       bootable/recovery/Android.bp:17:1 <-- previous definition here
error: Fox_11.0/bootable/recovery/gui/Android.bp:1:1: module "soong-libguitwrp_defaults" already defined
       bootable/recovery/gui/Android.bp:1:1 <-- previous definition here
error: Fox_11.0/bootable/recovery/minuitwrp/Android.bp:1:1: module "soong-libminuitwrp_defaults" already defined
       bootable/recovery/minuitwrp/Android.bp:1:1 <-- previous definition here
15:35:15 soong minibootstrap failed with: exit status 1

**Comment by Sushrut1101** [comment]
Which manifest version?

**Comment by Sushrut1101** [comment]
Not a Device tree issue
